"""added price column

Revision ID: 2f129e265132
Revises: 7079fff7df8d
Create Date: 2022-05-14 19:26:46.904458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f129e265132'
down_revision = '7079fff7df8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'price')
    # ### end Alembic commands ###
