"""added more

Revision ID: 7079fff7df8d
Revises: bf8462060e27
Create Date: 2022-05-14 19:15:35.731661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7079fff7df8d'
down_revision = 'bf8462060e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('event_name', sa.String(length=255), nullable=True))
    op.add_column('booking', sa.Column('event_location', sa.String(length=100), nullable=True))
    op.add_column('booking', sa.Column('event_date', sa.DateTime(), nullable=True))
    op.add_column('booking', sa.Column('start_time', sa.String(length=255), nullable=True))
    op.drop_column('booking', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('created_on', sa.DATETIME(), nullable=True))
    op.drop_column('booking', 'start_time')
    op.drop_column('booking', 'event_date')
    op.drop_column('booking', 'event_location')
    op.drop_column('booking', 'event_name')
    # ### end Alembic commands ###
